FROM nginx:alpine

# Kopiere die nginx-Konfiguration direkt in den Container
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"] 