version: '3.8'

services:
  # Frontend React application
  frontend:
    build:
      context: ./eu-hack
      dockerfile: Dockerfile
    container_name: eu-hack-frontend
    restart: unless-stopped
    networks:
      - eu-hack-network

  # Node.js proxy server
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: eu-hack-proxy
    restart: unless-stopped
    networks:
      - eu-hack-network

  # Nginx reverse proxy
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: eu-hack-nginx
    ports:
      - "8088:80"
    depends_on:
      - frontend
      - proxy
    restart: unless-stopped
    networks:
      - eu-hack-network

networks:
  eu-hack-network:
    driver: bridge 